name: Unit tests

on: [pull_request]

jobs:
  build:
    name: unit-tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: 'x64'
          java-package: 'jdk'
          cache: 'maven'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
        working-directory: ./melodify
