name: Unit tests

on: [pull_request, workflow_dispatch]

jobs:
  build:
    name: unit-tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: 'x64'
          java-package: 'jdk'
          cache: 'maven'
      - name: Maven install
        run: mvn -DskipTests install
        working-directory: ./melodify
      - name: Maven run tests
        run: mvn -DskipITs test
        working-directory: ./melodify
